<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Roshini" failures="1" tests="5" name="Default test" time="104.984" errors="0" timestamp="2025-09-09T23:54:27 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="11.369"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.954"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="13.061"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="51.39">
    <failure type="java.lang.AssertionError" message="Failed at invalid login -&amp;gt; enterInvalidOtp() expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed at invalid login -> enterInvalidOtp() expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.stepDefinition.Invalid.i_enter_the_otp(Invalid.java:199)
at âœ½.I enter the otp "9999"(file:///C:/Users/Roshini/eclipse-workspace/test_magicbricks/src/test/resources/Features/Invalid.feature:33)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.693"/>
</testsuite> <!-- Default test -->
